### ISSUE TITLE
Tutorial - Add object calisthenic on PhpStorm

### ISSUE THREAD

**Issue by roukmoute** [TomasVotruba/tomasvotruba.cz#114]
I have activated object calisthenic for all my projects via a composer global on phpstorm.
It can write a small article if you would like.

**Comment by TomasVotruba** [comment]
That would be great! Do you want to write on my blog?
There is actually better place, for more people - PHP commmunity blog. There is actually the same platform as here: 
https://github.com/pehapkari/pehapkari.cz/tree/master/source/_posts/2017

**Comment by roukmoute** [comment]
What is PHP commmunity blog?

**Comment by TomasVotruba** [comment]
https://pehapkari.cz/blog/

I've updated the link

**Comment by TomasVotruba** [comment]
I'm closing this here, feel free to send PR to https://github.com/pehapkari/pehapkari.cz
I'll help you to set it up
