### ISSUE TITLE
Wrong code snippet

### ISSUE THREAD

**Issue by jozefkoscak** [TomasVotruba/tomasvotruba.cz#136]
https://www.tomasvotruba.cz/blog/2017/08/21/5-useful-rules-from-symplify-coding-standard/

Code snippet in section "1. Array property should have default value" is same as code in section "2. Final Interface".

**Comment by TomasVotruba** [comment]
Thanks for reporting!

**Comment by TomasVotruba** [comment]
Congrats to your first issue BTW :tada:
