### ISSUE TITLE
Wrong deps

### ISSUE THREAD

**Issue by keradus** [TomasVotruba/tomasvotruba.cz#182]
Hi
Under https://www.tomasvotruba.cz/blog/2017/07/24/how-to-write-custom-fixer-for-php-cs-fixer-24/
this https://github.com/TomasVotruba/tomasvotruba.cz/blob/master/source/assets/images/posts/2017/php-cs-fixer-intro/php-cs-fixer-require.png is displayed as dependencies of PHP CS Fixer.
I don't know from where it was taken, but none of items on this list was ever used as PHP CS Fixer dependency.

**Comment by TomasVotruba** [comment]
Hey, nice catch. Its look like [symfony-demo](https://github.com/symfony/symfony-demo/blob/master/composer.json). 

Could you send PR with expected image?

**Comment by keradus** [comment]
nope. i will let you make pictures so it will looks same like other one

**Comment by TomasVotruba** [comment]
Nailed it :hammer:
