### ISSUE TITLE
[post] pros/cons Symfony/Nette/Laravel

### ISSUE THREAD

**Issue by mssimi** [TomasVotruba/tomasvotruba.cz#278]

**Comment by Lexinek** [comment]
I would love to know which framework use nowadays and why? What are upsides, downsides, expectations to the future?

**Comment by mssimi** [comment]
Reader should choose right framework for his use case or set of right packages from it. For example use framework A, if you want to develop fast and use framework B if your project is long term and so on.

**Comment by TomasVotruba** [comment]
This is related PR (not the post, just related topic): https://github.com/TomasVotruba/tomasvotruba.cz/pull/280

Could I ask you on review and/or adding examples?

**Comment by TomasVotruba** [comment]
- [ ] complete the page and add releaste post

**Comment by TomasVotruba** [comment]
Hey guys, I'm thinking of writing the post but I can only came up with "use what you love" argument :)

I guess there is no better way to do things.
