### ISSUE TITLE
Missing end of sentence

### ISSUE THREAD

**Issue by OndraM** [TomasVotruba/tomasvotruba.cz#322]
Hi,
in https://www.tomasvotruba.cz/blog/2017/07/24/how-to-write-custom-fixer-for-php-cs-fixer-24/#2-easypicks-first, there is this sentence:

> I start with implementing first 5 methods, to make

But it does not continue :)

**Comment by TomasVotruba** [comment]
Hey Ondra, thanks. I'll try to remember what I forgot :D

**Comment by TomasVotruba** [comment]
Todo: fix code highlight as well, probably remove PHP code example
