### ISSUE TITLE
[post] how to test private services in Symfony

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.cz#327]
This topic kind off fizzled out and people still keep asking about it.

Kinda like this one, just more dedicated:

https://www.tomasvotruba.cz/blog/2018/04/05/4-ways-to-speedup-your-symfony-development-with-packagebuilder/#2-drop-manual-code-public-true-code-for-every-service-you-test

---

Mentoin various approaches:

- Symfony KernelTestCase 
    - https://github.com/jakzal/phpunit-injector
    - https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing
    - https://github.com/SymfonyTest/symfony-bundle-test/blob/master/Readme.md
- Shopsys listing
- public all the time
    - CompilerPass

**Comment by TomasVotruba** [comment]
Btw, is something similar you'd like to publish @edobarnas ?

**Comment by TomasVotruba** [comment]
https://www.google.cz/search?q=symfony+test+private+services+site:stackoverflow.com&client=ms-android-google&prmd=vin&sa=X&ved=2ahUKEwjO_P_K347bAhVPL1AKHUxFCdAQrQIoBDADegQIAxAI&biw=412&bih=604&dpr=2.63

**Comment by TomasVotruba** [comment]
### Todo 

- [ ] reply on Stackoverflow with link - https://stackoverflow.com/search?q=symfony+tests+private+services

**Comment by TomasVotruba** [comment]
Better late then never. I already published my thoughts

**Comment by EdoBarnas** [comment]
Where did you publish your thoughts?

**Comment by TomasVotruba** [comment]
See referenced PR above
