### ISSUE TITLE
Gulp seems to not start the webserver

### ISSUE THREAD

**Issue by JanMikes** [TomasVotruba/tomasvotruba.cz#374]
It seems to be stuck after running `gulp` command. If i do in other tab `php -S localhost:8000 -t output` it is okay

<img width="512" alt="screenshot 2018-06-20 12 59 33" src="https://user-images.githubusercontent.com/3995003/41654468-d9c3262c-7489-11e8-8c00-6ff5bf6ebd05.png">

**Comment by TomasVotruba** [comment]
Btw, it happens to me as well in one of 50 runs. I guess some JavaScript vs server race condition.

Does it never work for you or just rarely?

**Comment by TomasVotruba** [comment]
It happens sometimes from my observation, when I'm working to fast. Rerun helps as solution
