### ISSUE TITLE
Cannot load image due to insecure connection

### ISSUE THREAD

**Issue by petrofcikmatus** [TomasVotruba/tomasvotruba.cz#536]
Hi,

in the article https://www.tomasvotruba.cz/blog/2018/02/12/sleep-shorter-to-get-62-percent-smarter/ is one image with url https://www.openworldmag.com/wp-content/uploads/2015/11/polyphasic-charts.jpg. That image cannot be loaded in Firefox due to insecure connection. It says that www.openworldmag.com uses an invalid security certificate.

Apple MacBook Air, MacOS Mojave, Firefox 62.0.3.

**Comment by TomasVotruba** [comment]
Hi Matúš,

thanks for reporting :+1:

**Comment by petrofcikmatus** [comment]
Happy to help.
