### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by enumag** [TomasVotruba/tomasvotruba.cz#612]
You have a bad example in your latest [article](https://www.tomasvotruba.cz/blog/2018/12/27/how-to-convert-all-your-symfony-service-configs-to-autodiscovery/#1-tags).

The `console.command` tag should NOT be added without command name and therefore you should not use autoconfiguration for commands. While it will still technically work, it makes the command [non-lazy](https://symfony.com/blog/new-in-symfony-3-4-lazy-commands) which hurts performance of all other commands.

**Comment by TomasVotruba** [comment]
I'm not sure I understand. Could you share a code where command is lazy-loaded with a tag?

**Comment by TomasVotruba** [comment]
I think you confused the syntax in post with lazy-loading: https://symfony.com/doc/current/console/commands_as_services.html#lazy-loading

I'll add one more example, so there is no space for doubts.

**Comment by TomasVotruba** [comment]
See #61š
